name: Build and Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node toolchain
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cache Rust cache
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: truegrf-rs

    - name: Install wasm-pack
      run: |
        cd truegrf-rs
        cargo install wasm-pack

    - name: Install node-modules
      run: |
        npm install

    - name: Patch node-modules
      run: |
        for patch in $(ls patches/*.patch); do
          patch -N -p1 < ${patch}
        done

    - name: Generate changelog listing
      run: |
        sh .github/generate-changelog-listing.sh

    - name: Install & build webapp
      run: |
        BASE_PATH="/TrueGRF" npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: build
